/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#cda72f",
        "inverse-surface": "#dce1fb",
        "surface-bright": "#33394c",
        "secondary-fixed-dim": "#bcc7de",
        "surface-container-low": "#151b2d",
        "secondary-fixed": "#d8e3fb",
        "on-secondary-container": "#aeb9d0",
        "secondary": "#bcc7de",
        "surface-dim": "#0c1324",
        "tertiary-fixed": "#ffe08b",
        "secondary-container": "#3e495d",
        "background": "#0c1324",
        "on-primary-container": "#9d7d00",
        "error-container": "#93000a",
        "primary": "#e9c349",
        "on-primary-fixed": "#241a00",
        "on-secondary": "#263143",
        "surface-variant": "#2e3447",
        "tertiary": "#ebc349",
        "outline-variant": "#45464d",
        "on-primary": "#3c2f00",
        "on-surface": "#dce1fb",
        "primary-fixed": "#ffe088",
        "surface-container-highest": "#2e3447",
        "inverse-primary": "#735c00",
        "surface-container-high": "#23293c",
        "surface-container-lowest": "#070d1f",
        "on-tertiary-container": "#4f3e00",
        "error": "#ffb4ab",
        "outline": "#909097",
        "surface": "#0c1324",
        "on-background": "#dce1fb",
        "surface-container": "#191f31",
        "on-surface-variant": "#c6c6cd",
        "on-error": "#690005",
        "primary-fixed-dim": "#e9c349",
        "on-tertiary-fixed-variant": "#584400",
        "tertiary-fixed-dim": "#eac249",
        "inverse-on-surface": "#2a3043",
        "surface-tint": "#e9c349",
        "on-secondary-fixed": "#111c2d",
        "on-tertiary-fixed": "#241a00",
        "on-tertiary": "#3d2f00",
        "primary-container": "#1f1700",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#3c475a",
        "on-primary-fixed-variant": "#574500"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
